$(document).ready(function(){
    $.get("/user").then(function(data){
        $("#username").text(data.username)
        $("#avatar").attr("src","https://cdn.discordapp.com/avatars/"+data.id+"/"+data.avatar)
        console.log(data)
    })
    $.get("/guilds").then(function(data){
        data.forEach(function(server){
            console.log(server)
            $.get("/campaigns").then(function(campaigns){
                if (campaigns[server.id]){
                    (campaigns.server.id).forEach(function(campaign){
                        console.log(campaign);
                    })
                }
            })
        })
    })
});